const map=L.map('map',{zoomControl:false,preferCanvas:true});L.control.zoom({position:'topleft'}).addTo(map);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);
const $=s=>document.querySelector(s),panel=$('#panel'),status=$('#status'),spin=$('#spinner');
const MC=L.Control.extend({options:{position:'topleft'},onAdd(){let b=L.DomUtil.create('button','menuControl');b.textContent='☰';L.DomEvent.disableClickPropagation(b);b.onclick=()=>panel.classList.toggle('closed');return b}});new MC().addTo(map);$('#close').onclick=()=>panel.classList.add('closed');
const cat={bicycle:['單車店','#0ea5e9','🚲',1],fuel:['加油站','#f59e0b','⛽',2],convenience:['便利店','#10b981','🏪',3],hotel:['酒店/旅館','#8b5cf6','🏨',4],restaurant:['餐廳','#ef4444','🍜',5]},enabled=new Set(Object.keys(cat));for(const [k,v] of Object.entries(cat)){$('#filters').insertAdjacentHTML('beforeend',`<label class=filter><input type=checkbox checked data-t=${k}><i class=dot style="background:${v[1]}"></i>${v[2]} ${v[0]}</label>`)}$('#filters').onchange=e=>{e.target.checked?enabled.add(e.target.dataset.t):enabled.delete(e.target.dataset.t);render()};
const f=L.polyline(LRM.forward,{color:'#2563eb',weight:5}),r=L.polyline(LRM.rebound,{color:'#f97316',weight:5});let mode='full';function routes(){return mode==='forward'?[LRM.forward]:mode==='rebound'?[LRM.rebound]:[LRM.forward,LRM.rebound]}function setMode(m){mode=m;map.removeLayer(f);map.removeLayer(r);if(m!=='rebound')f.addTo(map);if(m!=='forward')r.addTo(map);document.querySelectorAll('[data-m]').forEach(x=>x.classList.toggle('on',x.dataset.m===m));fit();render()}document.querySelectorAll('[data-m]').forEach(x=>x.onclick=()=>setMode(x.dataset.m));
function cp(ll,txt,x){L.marker(ll,{icon:L.divIcon({className:'',html:`<div class="poi cp">${x}</div>`,iconSize:[27,27]})}).addTo(map).bindPopup(txt)}cp(LRM.forward[0],'<b>Start / CP0</b><br>0 km','S');cp([LRM.meta.turnaround.lat,LRM.meta.turnaround.lon],`<b>Turnaround CP</b><br>${LRM.meta.turnaround.distanceKm} km`,'T');cp(LRM.rebound.at(-1),`<b>Finish</b><br>${LRM.meta.totalKm} km`,'F');
let pois=[],shown=[],layer=L.layerGroup().addTo(map),cache=new Map(),timer,controller;const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));function type(t){if(t.shop==='bicycle')return'bicycle';if(t.amenity==='fuel')return'fuel';if(t.shop==='convenience')return'convenience';if(['hotel','guest_house','hostel','motel'].includes(t.tourism))return'hotel';if(t.amenity==='restaurant')return'restaurant'}function addr(t){if(t['addr:full'])return t['addr:full'];let s=[t['addr:street'],t['addr:housenumber']].filter(Boolean).join(' ');return[s,t['addr:district'],t['addr:city'],t['addr:province'],t['addr:postcode']].filter(Boolean).join(', ')}function limit(){let z=map.getZoom();return z<12?0:z===12?12:z===13?18:z===14?24:30}
function select(a,n){let c=map.getCenter(),size=map.getSize(),cells=new Set(),out=[];a=a.filter(x=>enabled.has(x.type)).map(x=>({...x,d:c.distanceTo([x.lat,x.lon])})).sort((a,b)=>cat[a.type][3]-cat[b.type][3]||a.d-b.d);for(const x of a){let p=map.latLngToContainerPoint([x.lat,x.lon]),k=`${Math.floor(p.x/Math.max(90,size.x/5))}:${Math.floor(p.y/Math.max(90,size.y/4))}`;if(!cells.has(k)){out.push(x);cells.add(k)}if(out.length===n)return out}for(const x of a){if(!out.includes(x))out.push(x);if(out.length===n)break}return out}
function render(){layer.clearLayers();let max=limit();if(!max){status.innerHTML=`${label()}<br>Zoom 12 以下，POI 暫停載入`;return}let b=map.getBounds(),a=pois.filter(x=>b.contains([x.lat,x.lon]));shown=select(a,max);for(const x of shown){let v=cat[x.type],ic=L.divIcon({className:'',html:`<div class=poi style="background:${v[1]}">${v[2]}</div>`,iconSize:[27,27]});L.marker([x.lat,x.lon],{icon:ic}).addTo(layer).bindPopup(`<b>${esc(x.name)}</b><br>${v[0]}<br>${esc(x.address||'OSM 未提供地址')}<button class=copy data-id="${x.id}">複製名稱及地址</button>`)}status.innerHTML=`${label()}<br>目前範圍 ${a.length} 個，顯示 ${shown.length}/${max}`}
map.on('popupopen',e=>{let b=e.popup.getElement()?.querySelector('.copy');if(b)b.onclick=()=>{let x=pois.find(p=>p.id===b.dataset.id);navigator.clipboard.writeText(`${x.name}\n${x.address||'OSM 未提供地址'}`).then(()=>toast('已複製名稱及地址'))}});
function key(){let c=map.getCenter();return`${Math.min(map.getZoom(),16)}:${c.lat.toFixed(2)}:${c.lng.toFixed(2)}`}function query(b){let x=`${b.getSouth()},${b.getWest()},${b.getNorth()},${b.getEast()}`;return`[out:json][timeout:35];(nwr[shop=bicycle](${x});nwr[amenity=fuel](${x});nwr[shop=convenience](${x});nwr[tourism~"^(hotel|guest_house|hostel|motel)$"](${x});nwr[amenity=restaurant](${x}););out center tags;`}
async function load(){if(!limit()){render();return}let k=key();if(cache.has(k)){merge(cache.get(k));render();return}controller?.abort();controller=new AbortController();spin.classList.add('show');try{let data,q=query(map.getBounds().pad(.08));for(const ep of['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter']){try{let z=await fetch(ep,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'data='+encodeURIComponent(q),signal:controller.signal});if(z.ok){data=await z.json();break}}catch(e){if(e.name==='AbortError')throw e}}if(!data)throw Error();let a=data.elements.map(e=>{let t=e.tags||{},y=type(t),lat=e.lat??e.center?.lat,lon=e.lon??e.center?.lon;if(!y||lat==null)return null;return{id:e.type+'/'+e.id,lat,lon,type:y,name:t['name:zh']||t.name||t['brand:zh']||t.brand||cat[y][0],address:addr(t)}}).filter(Boolean);cache.set(k,a);merge(a);render()}catch(e){if(e.name!=='AbortError'){status.innerHTML=`${label()}<br>OSM POI 暫時無法載入`;toast('POI 載入失敗')}}finally{spin.classList.remove('show')}}function merge(a){let m=new Map(pois.map(x=>[x.id,x]));a.forEach(x=>m.set(x.id,x));pois=[...m.values()]}function schedule(){clearTimeout(timer);timer=setTimeout(load,650)}map.on('moveend zoomend',schedule);
function fit(){map.fitBounds(L.latLngBounds(routes().flat()),{padding:[30,30]})}$('#fit').onclick=fit;$('#locate').onclick=()=>map.locate({setView:true,maxZoom:15,enableHighAccuracy:true});let user;map.on('locationfound',e=>{if(user)map.removeLayer(user);user=L.circleMarker(e.latlng,{radius:8,color:'#fff',weight:3,fillColor:'#2563eb',fillOpacity:1}).addTo(map).bindPopup(`我的位置<br>精度約 ${Math.round(e.accuracy)} m`).openPopup()});function label(){return mode==='forward'?`Forward: ${LRM.meta.forwardKm} km`:mode==='rebound'?`Rebound: ${LRM.meta.reboundKm} km`:`Full: ${LRM.meta.totalKm} km`}function toast(s){let t=$('#toast');t.textContent=s;t.className='show';setTimeout(()=>t.className='',1800)}setMode('full');
